/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empmgmt.gui;

import empmgmt.dbutil.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class OptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionsFrame
     */
    public OptionsFrame() {
        initComponents(); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbAddEmployee = new javax.swing.JRadioButton();
        jrbSearchEmployee = new javax.swing.JRadioButton();
        jrbShowAllEmployee = new javax.swing.JRadioButton();
        jrbQuit = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jrbUpdate = new javax.swing.JRadioButton();
        jrbDelete = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Select Your Choice");

        jrbAddEmployee.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbAddEmployee);
        jrbAddEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbAddEmployee.setForeground(new java.awt.Color(240, 240, 240));
        jrbAddEmployee.setText("Add Employee");

        jrbSearchEmployee.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbSearchEmployee);
        jrbSearchEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbSearchEmployee.setForeground(new java.awt.Color(240, 240, 240));
        jrbSearchEmployee.setText("Search Employee");

        jrbShowAllEmployee.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbShowAllEmployee);
        jrbShowAllEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbShowAllEmployee.setForeground(new java.awt.Color(240, 240, 240));
        jrbShowAllEmployee.setText("Show All Employees");

        jrbQuit.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbQuit);
        jrbQuit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbQuit.setForeground(new java.awt.Color(240, 240, 240));
        jrbQuit.setText("Quit");

        btnDoTask.setBackground(new java.awt.Color(0, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(240, 240, 240));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        jrbUpdate.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbUpdate);
        jrbUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jrbUpdate.setText("Update Employee");

        jrbDelete.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbDelete);
        jrbDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbDelete.setForeground(new java.awt.Color(255, 255, 255));
        jrbDelete.setText("Delete Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbSearchEmployee)
                            .addComponent(jrbAddEmployee)
                            .addComponent(jrbShowAllEmployee)
                            .addComponent(jrbUpdate)
                            .addComponent(jrbDelete)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnDoTask))
                            .addComponent(jrbQuit))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jrbAddEmployee)
                .addGap(18, 18, 18)
                .addComponent(jrbSearchEmployee)
                .addGap(18, 18, 18)
                .addComponent(jrbShowAllEmployee)
                .addGap(18, 18, 18)
                .addComponent(jrbUpdate)
                .addGap(18, 18, 18)
                .addComponent(jrbDelete)
                .addGap(18, 18, 18)
                .addComponent(jrbQuit)
                .addGap(35, 35, 35)
                .addComponent(btnDoTask)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
       if(validateInput()==false){
           JOptionPane.showMessageDialog(null, "Please Make a Selection first!","Error",JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(jrbAddEmployee.isSelected()){
           AddEmployeeFrame addEmp=new AddEmployeeFrame();
           addEmp.setVisible(true);
           this.dispose();
       }
       else if(jrbSearchEmployee.isSelected()){
           SearchEmployeeFrame searchEmp=new SearchEmployeeFrame();
           searchEmp.setVisible(true);
           this.dispose();
       }
        else if(jrbShowAllEmployee.isSelected()){
           ViewAllEmployeeFrame viewAllEmp=new ViewAllEmployeeFrame();
           viewAllEmp.setVisible(true);
           this.dispose(); 
       }
        else if(jrbUpdate.isSelected()){
            UpdateEmployeeFrame updateEmp=new UpdateEmployeeFrame();
            updateEmp.setVisible(true);
            this.dispose();
        }
        else if(jrbDelete.isSelected()){
            DeleteEmployeeFrame deleteEmp=new DeleteEmployeeFrame();
            deleteEmp.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Thank you for using the App!","Thanks",JOptionPane.INFORMATION_MESSAGE);
            DBConnection.closeConnection();
            System.exit(0);
        }
    }//GEN-LAST:event_btnDoTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbAddEmployee;
    private javax.swing.JRadioButton jrbDelete;
    private javax.swing.JRadioButton jrbQuit;
    private javax.swing.JRadioButton jrbSearchEmployee;
    private javax.swing.JRadioButton jrbShowAllEmployee;
    private javax.swing.JRadioButton jrbUpdate;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
        if(jrbAddEmployee.isSelected()==false
                &&jrbSearchEmployee.isSelected()==false
                &&jrbShowAllEmployee.isSelected()==false
                &&jrbQuit.isSelected()==false&&jrbUpdate.isSelected()==false
                &&jrbDelete.isSelected()==false){
            return false;
        }
        return true;
    }
}
